version: '2'
services:
    currencyexchange-app:
        image: currencyexchange
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://currencyexchange-mysql:3306/currencyexchange?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    currencyexchange-mysql:
        extends:
            file: mysql.yml
            service: currencyexchange-mysql
